server:
  port: 7000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
   # filters: stat  #开启监控过滤器
  application:
    name: SCW-USER
  redis:
    password: 123456
    host: 192.168.18.131
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    path: D:\Program\SpringBoot\log
  level:
    com:
      hyd: debug  #设置路径bu不然报错

sms:
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method: POST
  appCode: APPCODE 833133ae3dcc4839ae5d938d72f19e2b
#  appCode: APPCODE f44b9437185349ad89f5504b8e01f393

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/offcn/user/mapper/*.xml